language: node_js

node_js:
  - "8"

script:
      - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: false
  local_dir: dist
  target_branch: gh-pages
  name: kezhenxu94
  email: kezhenxu94@apache.org
  on:
    branch: master

notifications:
  email:
    recipients:
      - kezhenxu94@apache.org
    on_success: change
    on_failure: always
